### ISSUE TITLE
TypeError when trying to gather logs (SauceLabs / IE)

### ISSUE THREAD

**Issue by alexgibson** [pytest-dev/pytest-selenium#288]
When using pytest-selenium to run tests in Saucelabs using Internet Explorer on Windows 10, we currently get an error when trying to gather logs after the test run:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pytest_parallel/__init__.py", line 93, in run
INTERNALERROR>     run_test(self.session, item, None)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pytest_parallel/__init__.py", line 54, in run_test
INTERNALERROR>     item.ihook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pytest_rerunfailures.py", line 497, in pytest_runtest_protocol
INTERNALERROR>     reports = runtestprotocol(item, nextitem=nextitem, log=False)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/_pytest/runner.py", line 126, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/_pytest/runner.py", line 217, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pytest_selenium/pytest_selenium.py", line 300, in pytest_runtest_makereport
INTERNALERROR>     _gather_logs(item, report, driver, summary, extra)
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/pytest_selenium/pytest_selenium.py", line 360, in _gather_logs
INTERNALERROR>     for name in types:
INTERNALERROR> TypeError: 'NoneType' object is not iterable
```

**Comment by isaulv** [comment]
I suspect that the API to sauce labs has evolved and thus we need to update the code to reflect these changes. If you can submit a patch I'll get it merged at the very least.

**Comment by BeyondEvil** [comment]
@alexgibson Ping
