### ISSUE TITLE
always have Element is not clickable at point 

### ISSUE THREAD

**Issue by HackToday** [pytest-dev/pytest-selenium#74]
I have following version installed
``` 
pytest==2.9.2
pytest-selenium==1.3.1
selenium == 2.53.0
```

And have my app  test like below:

```

 26     def click_app_save_button(self):
 27         save_elem = self.selenium.find_element(*self._app_save_button_locator)
 28         ActionChains(self.selenium).move_to_element(save_elem).click().perform()
```

Hit errors like below:

```

02:59:00.034 INFO - Executing: [find element: By.cssSelector: button.btn.green])
02:59:00.453 INFO - Done: [find element: By.cssSelector: button.btn.green]
02:59:00.509 INFO - Executing: [mousemove: 11 false])
02:59:00.607 INFO - Done: [mousemove: 11 false]
02:59:00.661 INFO - Executing: [click: nothing])
02:59:00.693 WARN - Exception thrown
org.openqa.selenium.WebDriverException: Element is not clickable at point (477.25, 588). Other element would receive the click: <div style="z-index: 10050;" class="modal-scrollable"></div> (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '5963827d09ef', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-123.el7.x86_64', java.version: '1.8.0_03-Ubuntu'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0.2, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7085aa70-86d2-417f-9ec2-a2bf40572cd5
	at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.click(RemoteMouse.java:59)
	at org.openqa.selenium.support.events.internal.EventFiringMouse.click(EventFiringMouse.java:42)
	at org.openqa.selenium.remote.server.handler.interactions.ClickInSession.call(ClickInSession.java:40)
	at org.openqa.selenium.remote.server.handler.interactions.ClickInSession.call(ClickInSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
02:59:00.693 WARN - Exception: Element is not clickable at point (477.25, 588). Other element would receive the click: <div style="z-index: 10050;" class="modal-scrollable"></div> (WARNING: The server did not provide any stacktrace information)

```

**Comment by RonnyPfannschmidt** [comment]
that looks like a selenium issue

**Comment by HackToday** [comment]
i have solved this, it was because ajax issue, some background job did, which cause such button not available some time. so I add wait until related element appear which solved that
